language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
